### ISSUE TITLE
Apparently Header files not properly installed - fatal error: flex_sync/approximate_sync.hpp: No such file or directory

### ISSUE THREAD

**Issue by tomcreutz** [berndpfrommer/flex_sync#1]
Hi @berndpfrommer,
I'm currently trying to build the ros2 branch of your aprilslam package as I'm thinking about using it for a project (I'm aware that it is still heavily WIP).
On a fresh install (and newly created workspace) I am not able to build the aprilslam library as it couldn't find the header files of this package.

Changing line 51-53 of the CMakeLists.txt file to the following resolved the issue for me. With the `${CMAKE_INSTALL_INCLUDEDIR}` as install destination it gets installed into the `install/` folder directly instead of the `install/include/` directory. Here is the proposed install command to fix the issue:

```
install(DIRECTORY
  include
    DESTINATION include/)
```

Please let me know if you're able to reproduce this error and if I should open a pull request with the proposed fix (as it is quite trivial).

**Comment by berndpfrommer** [comment]
Just pushed that change. I had it already sitting in my workspace but hadn't pushed it yet.
The reason being that the TagSLAM ros2 branch is *totally unusable*. It's not even close. I'm at least 2 weeks away from getting anything I could call "barely working" off the ground, and I'm working pretty much full time on it.
I spend a lot of time cleaning up the dependencies, right now with respect to the apriltag detector. I'm hoping the overall architecture will look cleaner so I can release tagslam to rosdistro one day.

**Comment by berndpfrommer** [comment]
@tomcreutz please follow the progress on [this issue](https://github.com/berndpfrommer/tagslam_root/issues/20) if you are still interested in using tagslam on ROS2. Bottom line: not quite there yet, but getting there.
